version: "3"

services:
  nginx-ciitev_web-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx_ciitev_web
    image: ciitev_pgloader
    volumes:
      - .:/code
    command:
      - /start
    # networks:
    #   - migraciones_default
    network_mode: "host"

# networks:
#   migraciones_default:
#     external: true